### ISSUE TITLE
`udata init` causes import related exception when using Python 3.10

### ISSUE THREAD

**Issue by tboye** [opendatateam/udata#2795]
## Detailed Description

When following [Getting Started](https://udata.readthedocs.io/en/stable/getting-started) with Python 3.10, data initialization step fails with `ImportError: cannot import name 'Iterable' from 'collections'` error. This might be due to the fact `Iterable` abstract class was removed from `collections` in Python 3.10. It would be great to either make udata compatible with Python 3.10 or state that it's currently not compatible (currently the requirement is phrased as Python 3.7+).

## Context

When I follow Getting Started, I want to avoid preventible errors, so I can get started quicker.

## Possible Implementation

**Option 1** -- a change in the code along the following lines:

```
try:
    from collections.abc import Iterable
except ImportError:
    from collections import Iterable
```
There might be additional changes needed though.

**Option 2** -- modify Python version requirement in the documentation.

## Your Environment

* Operating System and version (desktop or mobile): MacOS (might be irrelevant) + Python 3.10

**Comment by tboye** [comment]
Just wanted to add that dev environment setup process is overall pretty smooth despite a few bumps related to Python dependencies. Also, my general compliments to `udata` team. Very neat project, back and front!

**Comment by maudetes** [comment]
Thank you for the feedback!
We hadn't tested yet on python 3.10 but now we should indeed specify the correct requirement. I've made a PR: https://github.com/opendatateam/udata/pull/2798.
If you've made it work with python 3.10, don't hesitate to open a PR, else I think we won't focus on it for now.

For you information, you should know that it's running on python 3.7 in our prod environment, even if we develop using python up to 3.9.

**Comment by tboye** [comment]
Good to know that you use 3.7 in production, thanks.

I made an attempt to fix it for 3.10 but the error I shared appeared to be just the first one. So I stopped right at the second issue (who knows, maybe it was the last one) as I also thought it's not really worth it.
